# examples/test_hw_pricer.py

from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd

# -------------------------------------------------------------------
# Ensure we can import from src/muni_core during dev
# -------------------------------------------------------------------
THIS_FILE = Path(__file__).resolve()
REPO_ROOT = THIS_FILE.parents[1]        # D:\muni-lab-core
SRC_ROOT = REPO_ROOT / "src"            # D:\muni-lab-core\src

if str(SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(SRC_ROOT))

# Now imports from the package
from muni_core.config.loader import AppConfig
from muni_core.pricing import price_level_coupon_bond_hw


def main() -> None:
    # 1) Load config
    cfg_path = (REPO_ROOT / "config" / "example_config.yaml").resolve()
    print(f"[INFO] Using config: {cfg_path}")
    app_cfg = AppConfig.from_yaml(cfg_path)

    # 2) Load prebuilt history parquet (already generated by tests.test_config_and_sources)
    history_path = app_cfg.curves.history_file
    print(f"[INFO] Loading history from: {history_path}")
    history_df = pd.read_parquet(history_path)

    # 3) Price a simple level-coupon bond via HW lattice
    price = price_level_coupon_bond_hw(
        history_df=history_df,
        app_cfg=app_cfg,
        maturity_years=10.0,      # 10-year maturity
        coupon_rate=0.04,         # 4% annual coupon
        freq_per_year=2,          # semi-annual coupons
        face=100.0,               # par 100
        curve_key="AAA_MUNI_SPOT",
        step_years=0.5,           # semi-annual HW lattice step
    )

    print(f"[RESULT] HW price for 10Y 4% AAA_MUNI_SPOT bond: {price:.6f}")


if __name__ == "__main__":
    main()
